Задание 3
1.1 Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU 1.2 Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя 1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.) 1.4 Удалите признаки Memory и ScreenResolution

In [1]:
import pandas as pd

df = pd.read_csv("laptop_price.csv", sep= ',',encoding='windows-1251')
df.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [2]:
df["Cpu_Company"]=df["Cpu"].apply(lambda x: x.split(" ")[0])
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

1.2 Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя

In [3]:
df['Memory'].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [4]:
def memory(x):
    res = x.split()[0]
    if res.endswith('GB'):
        result = res.replace('GB', '')
    elif res.endswith('TB'):
        result = float(res.replace('TB', '')) * 1024
    return int(result)

In [5]:
df['Memory_Amount'] = df['Memory'].apply(memory)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256

1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.)

In [6]:
df['Memory_Type'] = df['Memory'].apply(lambda x: x.replace('', '').split('B')[-1])
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

In [7]:
df['Memory_Type'].value_counts()

Memory_Type
 SSD              641
 HDD              576
 Flash Storage     74
 Hybrid            12
Name: count, dtype: int64

1.4 Удалите признаки Memory и ScreenResolution

In [8]:
df.drop(columns=['Memory', 'ScreenResolution'], inplace=True)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

Задание 2.
2.1 Создайте признак SSD, который изначально равен 0

In [9]:
df['SSD'] = 0
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0

2.2 Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD

In [10]:
df.loc[df['Memory_Type'] == 'SSD','SSD'] = 1
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0

In [11]:
df['TEMP_SSD'] = 'SSD'
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,TEMP_SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,0,SSD
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0,SSD

In [12]:
df.loc[df['TEMP_SSD'] == 'SSD','SSD'] = 1
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,TEMP_SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,1,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,1,SSD
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,1,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,1,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,1,SSD

2.3 Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [13]:
df['Weight'] = df['Weight'].str.replace('kg','').astype ('float')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,TEMP_SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,1,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,Flash Storage,1,SSD
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD,1,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD,1,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD,1,SSD

In [14]:
df.dtypes

laptop_ID          int64
Company           object
Product           object
TypeName          object
Inches           float64
Cpu               object
Ram               object
Gpu               object
OpSys             object
Weight           float64
Price_euros      float64
Cpu_Company       object
Memory_Amount      int64
Memory_Type       object
SSD                int64
TEMP_SSD          object
dtype: object

Создайте датафрейм с клиентами:
clients = pd.DataFrame({
'client_id': [45, 32, 67, 33, 43],
'laptop_id': [506, 398, 710, 120, 1999]
})
laptop_id - это индексы датафрейма с ноутбуками
3.1 Присоедините к таблице clients данные по ноутбукам через метод join
3.2 Присоедините к таблице clients данные по ноутбукам через метод merge
Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

In [15]:
clients = pd.DataFrame({
 'client_id': [45, 32, 67, 33, 43],
 'laptop_id': [506, 398, 710, 120, 1999]
})
clients

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

3.1 Присоедините к таблице clients данные по ноутбукам через метод join

In [16]:
clients_id = clients.set_index('laptop_id')

In [17]:
clients_id.join(df)

,client_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,TEMP_SSD
laptop_id,,,,,,,,,,,,,,,,,
506,45,513.0,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256.0,HDD,1.0,SSD
398,32,405.0,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256.0,SSD,1.0,SSD
710,67,718.0,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128.0,HDD,1.0,SSD
120,33,123.0,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024.0,HDD,1.0,SSD
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3.2 Присоедините к таблице clients данные по ноутбукам через метод merge
Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

In [18]:
merge = clients.merge(df, left_on='laptop_id', right_on='laptop_ID')
merge

,client_id,laptop_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,TEMP_SSD
0,45,506,506,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256,SSD,1,SSD
1,67,710,710,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024,HDD,1,SSD
2,33,120,120,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,256,HDD,1,SSD

Задание 4.
Составьте несколько сводных таблиц
4.1 Найдите среднюю стоимость ноутбуков в зависимости от компании производителя
Отсортируйте от меньшей стоимости к большей

In [19]:
df.groupby('Company')['Price_euros'].mean().sort_values()

Company
Vero          217.425000
Mediacom      295.000000
Chuwi         314.296667
Acer          626.775825
Fujitsu       729.000000
HP           1067.774854
Lenovo       1086.384444
Asus         1104.169367
Xiaomi       1133.462500
Dell         1186.068990
Toshiba      1267.812500
Samsung      1413.444444
Huawei       1424.000000
Apple        1564.198571
Microsoft    1612.308333
Google       1677.666667
MSI          1728.908148
LG           2099.000000
Razer        3346.142857
Name: Price_euros, dtype: float64

4.2 Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [20]:
df.groupby('Cpu_Company')['Price_euros'].agg(['min', 'mean', 'max'])

               min         mean     max
Cpu_Company
AMD          199.0   560.638871  2199.0
Intel        174.0  1152.214145  6099.0
Samsung      659.0   659.000000   659.0

In [21]:
df.groupby('Cpu_Company').agg({'Price_euros': ['min', 'mean', 'max']})

            Price_euros
                    min         mean     max
Cpu_Company
AMD               199.0   560.638871  2199.0
Intel             174.0  1152.214145  6099.0
Samsung           659.0   659.000000   659.0

4.3 Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [22]:
df.pivot_table(index='Cpu_Company',
               columns='Ram',
               values='Weight',
               aggfunc='count')

Ram          12GB   16GB  24GB   2GB  32GB    4GB  64GB   6GB    8GB
Cpu_Company
AMD           2.0    3.0   NaN   1.0   NaN   31.0   NaN  13.0   12.0
Intel        23.0  197.0   3.0  21.0  17.0  343.0   1.0  28.0  607.0
Samsung       NaN    NaN   NaN   NaN   NaN    1.0   NaN   NaN    NaN

4.4 Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [23]:
df.pivot_table(index='OpSys',
               columns='Memory_Amount',
               values='Price_euros',
               aggfunc='mean',
               fill_value=0)

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
OpSys,,,,,,,,,,,,,
Android,0,0.00,0.000000,434.000000,0.000000,0.0,0,0.000000,0.000000,0,0.000000,0.000000,0.0000
Chrome OS,0,305.38,412.454545,774.333333,1275.000000,0.0,0,1559.000000,0.000000,0,2199.000000,0.000000,0.0000
Linux,0,0.00,0.000000,0.000000,742.250000,0.0,0,811.638125,389.056364,0,0.000000,581.401290,0.0000
Mac OS X,0,0.00,0.000000,0.000000,1099.000000,0.0,0,1311.994000,0.000000,0,1222.000000,0.000000,0.0000
No OS,0,0.00,0.000000,0.000000,562.140000,0.0,0,782.989286,404.675385,0,1098.500000,540.539600,594.0000
Windows 10,2249,0.00,270.001471,499.716000,1026.489167,1073.5,3100,1334.456872,664.717647,0,1911.985285,904.827906,666.9475
Windows 10 S,0,0.00,0.000000,308.995000,1039.000000,0.0,0,1668.950000,0.000000,0,2589.000000,0.000000,0.0000
Windows 7,0,0.00,0.000000,0.000000,1320.323333,1199.0,0,1846.466800,924.048333,1002,2235.396667,1539.666667,0.0000
macOS,0,0.00,0.000000,0.000000,1119.315000,0.0,0,1600.370000,0.000000,0,2180.870000,0.000000,0.0000

Задание 5*.
Ответьте на несколько вопросов

5.1 Ноутбуков каких компаний и с каким процессором больше?

In [24]:

pd.crosstab(index=df['Company'],
            columns=df['Cpu_Company'])

Cpu_Company  AMD  Intel  Samsung
Company
Acer          10     93        0
Apple          0     21        0
Asus          11    147        0
Chuwi          0      3        0
Dell           0    297        0
Fujitsu        0      3        0
Google         0      3        0
HP            25    249        0
Huawei         0      2        0
LG             0      3        0
Lenovo        16    281        0
MSI            0     54        0
Mediacom       0      7        0
Microsoft      0      6        0
Razer          0      7        0
Samsung        0      8        1
Toshiba        0     48        0
Vero           0      4        0
Xiaomi         0      4        0

5.2 С каким типом памяти и с каким объемом памяти больше ноутбуков?

In [25]:
pd.crosstab(index=df['Memory_Type'],
            columns=df['Memory_Amount'])

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
Memory_Type,,,,,,,,,,,,,
Flash Storage,0,7,38,15,4,0,0,8,0,0,2,0,0
HDD,0,0,1,1,97,0,0,85,132,0,17,227,16
Hybrid,0,0,0,0,0,0,0,1,0,1,1,9,0
SSD,1,3,6,1,76,5,1,414,0,0,120,14,0